language: node_js
node_js:
 - “7”
script:
 - echo “Deploy!!”
install:
 - npm install -g firebase-tools
after_success:
 - firebase deploy - project shavtzakon - token 1/6ohhmovTetVkgdbE6MqmncQI7iSwDhJGxwj80SFBLSauFZYT2H8hXnXOZysx04Fx
